# -*- coding: utf-8 -*-
"""Stock Data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1I9FoKpVf932fQRrt6BWiiJf0Wnco2AFL
"""

from datetime import date
from nsepy import get_history
import time
import pandas as pd

nse_list = ['ADANIPORTS','ASIANPAINT','AXISBANK','BAJAJ-AUTO','BAJFINANCE','BAJAJFINSV','BHARTIARTL','INFRATEL','BPCL','BRITANNIA','CIPLA','COALINDIA','DRREDDY','EICHERMOT','GAIL','GRASIM','HCLTECH','HDFC','HDFCBANK','HEROMOTOCO','HINDALCO','HINDUNILVR','ICICIBANK','INDUSINDBK','INFY','IOC','ITC','JSWSTEEL','KOTAKBANK','LT','M&M','MARUTI','NESTLEIND','NTPC','ONGC','POWERGRID','RELIANCE','SHREECEM','SBIN','SUNPHARMA','TCS','TATAMOTORS','TATASTEEL','TECHM','TITAN','ULTRACEMCO','UPL','VEDL','WIPRO','ZEEL']

stocks = []
try:
 for i, elem in enumerate(nse_list):
  print(i,elem)
  stock = get_history(symbol=elem,
                   start=date(2015,1,1),
                   end=date(2020,5,15))
  
  if stock is not None:
   stocks.append(stock)
  
  time.sleep(10)
 stocks = pd.concat(stocks)
 stocks.to_csv(r'50_nifty_stock_data_test_tut1.csv')  
 

except:
 stocks = pd.concat(stocks)
 stocks.to_csv(r'50_nifty_stock_data_test_tut1.csv')





